// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"Week04/internal/dao"
	"Week04/internal/server/http"
	"Week04/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db, cleanup, err := dao.NewDb()
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup2, err := dao.New(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService, cleanup3, err := service.New(daoDao)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpServer, cleanup4, err := http.New(serviceService)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup5, err := NewApp(httpServer)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
